[package]
name = "simple-wasm"
version = "0.1.0"
edition = "2021"
description = "Move compiler wasm binding"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
