[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { workspace = true }
move-compiler = { git = "https://github.com/aptos-labs/aptos-core", branch = "main" }
getrandom = { workspace = true }
